---
title: "Plotly"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, echo = FALSE, message = FALSE, warning = FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)
library(p8105.datasets)
library(ggridges)
library(viridis)

```

```{r, echo = FALSE, message = FALSE, warning = FALSE}
weather_df = 
  rnoaa::meteo_pull_monitors(c("USW00094728", "USC00519397", "USS0023B17S"),
                      var = c("PRCP", "TMIN", "TMAX"), 
                      date_min = "2017-01-01",
                      date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY", 
                      USC00519397 = "Waikiki_HA",
                      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
weather_df
```



Column {data-width=650}
-----------------------------------------------------------------------

### Minimum and Maximum Temperatures within Dataset

```{r, echo = FALSE, message = FALSE, warning = FALSE}
weather_df %>%
 plot_ly(
    x = ~tmin, y = ~tmax, type = "scatter", mode = "markers", alpha = 0.5)
```

Column {data-width=350}
-----------------------------------------------------------------------

### Minimum Temperatures by Location

```{r, echo = FALSE, message = FALSE, warning = FALSE}
weather_df %>%
  plot_ly(y = ~tmin, color = ~name, type = "violin")
```

### Precipitation by Location

```{r, echo = FALSE, message = FALSE, warning = FALSE}
weather_df %>%
  plot_ly(y = ~prcp, color = ~name, type = "box")
```

